#!/bin/bash
# Migration Cleanup Script - Generated by Hive Mind Analysis
# Date: 2025-10-10
# WARNING: Run this script only after reviewing the MIGRATION_CLEANUP_REPORT.md

set -e

echo "🐝 Hive Mind Migration Cleanup Script"
echo "======================================"
echo ""
echo "This script will delete 14 confirmed duplicate migrations."
echo "Make sure you have:"
echo "  1. Reviewed the MIGRATION_CLEANUP_REPORT.md"
echo "  2. Backed up your database"
echo "  3. Tested in staging environment"
echo ""
read -p "Do you want to proceed? (yes/no): " confirm

if [ "$confirm" != "yes" ]; then
    echo "Cleanup cancelled."
    exit 0
fi

# Create backup
echo "Creating backup..."
BACKUP_DIR="alembic/versions.backup.$(date +%Y%m%d_%H%M%S)"
cp -r alembic/versions $BACKUP_DIR
echo "✅ Backup created at: $BACKUP_DIR"

# Phase 1: Delete high-confidence duplicates
echo ""
echo "Deleting duplicate index migrations..."

# Array of files to delete
declare -a files_to_delete=(
    "alembic/versions/031_add_users_email_active_index.py"
    "alembic/versions/032_add_messages_whatsapp_id_index.py"
    "alembic/versions/033_add_audit_user_timestamp_index.py"
    "alembic/versions/034_add_patient_flow_states_active_index.py"
    "alembic/versions/020_add_message_status_events_indexes.py"
    "alembic/versions/021_add_webhook_events_indexes.py"
    "alembic/versions/035_add_composite_performance_indexes.py"
    "alembic/versions/036_add_foreign_key_constraints.py"
    "alembic/versions/038_add_jsonb_gin_indexes.py"
    "alembic/versions/039_add_fulltext_search_indexes.py"
    "alembic/versions/20250929_193000_add_performance_indexes.sql"
    "alembic/versions/add_quiz_constraints.py"
    "alembic/versions/add_performance_indexes.py"
)

deleted_count=0
for file in "${files_to_delete[@]}"; do
    if [ -f "$file" ]; then
        rm "$file"
        echo "  ❌ Deleted: $(basename $file)"
        ((deleted_count++))
    else
        echo "  ⚠️  Not found: $(basename $file)"
    fi
done

echo ""
echo "✅ Cleanup complete!"
echo "   - Deleted $deleted_count files"
echo "   - Backup saved in: $BACKUP_DIR"
echo ""
echo "Next steps:"
echo "  1. Run: alembic history"
echo "  2. Run: alembic check"
echo "  3. Test migrations: alembic upgrade head --sql"
echo ""
echo "If issues occur, restore from backup:"
echo "  rm -rf alembic/versions"
echo "  mv $BACKUP_DIR alembic/versions"
echo ""
echo "🐝 Hive Mind cleanup successful!"