@echo off
REM Migration Cleanup Script - Generated by Hive Mind Analysis
REM Date: 2025-10-10
REM WARNING: Run this script only after reviewing the MIGRATION_CLEANUP_REPORT.md

echo ================================
echo Hive Mind Migration Cleanup Script
echo ================================
echo.
echo This script will delete 14 confirmed duplicate migrations.
echo Make sure you have:
echo   1. Reviewed the MIGRATION_CLEANUP_REPORT.md
echo   2. Backed up your database
echo   3. Tested in staging environment
echo.

set /p confirm="Do you want to proceed? (yes/no): "
if not "%confirm%"=="yes" (
    echo Cleanup cancelled.
    exit /b 0
)

REM Create backup
echo Creating backup...
for /f "tokens=1-3 delims=/ " %%a in ('date /t') do set DATE=%%c%%a%%b
for /f "tokens=1-2 delims=: " %%a in ('time /t') do set TIME=%%a%%b
set BACKUP_DIR=alembic\versions.backup.%DATE%_%TIME: =%

xcopy /E /I /Y alembic\versions %BACKUP_DIR%
echo Backup created at: %BACKUP_DIR%

echo.
echo Deleting duplicate index migrations...

REM Delete files
set deleted_count=0

if exist "alembic\versions\031_add_users_email_active_index.py" (
    del "alembic\versions\031_add_users_email_active_index.py"
    echo   Deleted: 031_add_users_email_active_index.py
    set /a deleted_count+=1
)

if exist "alembic\versions\032_add_messages_whatsapp_id_index.py" (
    del "alembic\versions\032_add_messages_whatsapp_id_index.py"
    echo   Deleted: 032_add_messages_whatsapp_id_index.py
    set /a deleted_count+=1
)

if exist "alembic\versions\033_add_audit_user_timestamp_index.py" (
    del "alembic\versions\033_add_audit_user_timestamp_index.py"
    echo   Deleted: 033_add_audit_user_timestamp_index.py
    set /a deleted_count+=1
)

if exist "alembic\versions\034_add_patient_flow_states_active_index.py" (
    del "alembic\versions\034_add_patient_flow_states_active_index.py"
    echo   Deleted: 034_add_patient_flow_states_active_index.py
    set /a deleted_count+=1
)

if exist "alembic\versions\020_add_message_status_events_indexes.py" (
    del "alembic\versions\020_add_message_status_events_indexes.py"
    echo   Deleted: 020_add_message_status_events_indexes.py
    set /a deleted_count+=1
)

if exist "alembic\versions\021_add_webhook_events_indexes.py" (
    del "alembic\versions\021_add_webhook_events_indexes.py"
    echo   Deleted: 021_add_webhook_events_indexes.py
    set /a deleted_count+=1
)

if exist "alembic\versions\035_add_composite_performance_indexes.py" (
    del "alembic\versions\035_add_composite_performance_indexes.py"
    echo   Deleted: 035_add_composite_performance_indexes.py
    set /a deleted_count+=1
)

if exist "alembic\versions\036_add_foreign_key_constraints.py" (
    del "alembic\versions\036_add_foreign_key_constraints.py"
    echo   Deleted: 036_add_foreign_key_constraints.py
    set /a deleted_count+=1
)

if exist "alembic\versions\038_add_jsonb_gin_indexes.py" (
    del "alembic\versions\038_add_jsonb_gin_indexes.py"
    echo   Deleted: 038_add_jsonb_gin_indexes.py
    set /a deleted_count+=1
)

if exist "alembic\versions\039_add_fulltext_search_indexes.py" (
    del "alembic\versions\039_add_fulltext_search_indexes.py"
    echo   Deleted: 039_add_fulltext_search_indexes.py
    set /a deleted_count+=1
)

if exist "alembic\versions\20250929_193000_add_performance_indexes.sql" (
    del "alembic\versions\20250929_193000_add_performance_indexes.sql"
    echo   Deleted: 20250929_193000_add_performance_indexes.sql
    set /a deleted_count+=1
)

if exist "alembic\versions\add_quiz_constraints.py" (
    del "alembic\versions\add_quiz_constraints.py"
    echo   Deleted: add_quiz_constraints.py
    set /a deleted_count+=1
)

if exist "alembic\versions\add_performance_indexes.py" (
    del "alembic\versions\add_performance_indexes.py"
    echo   Deleted: add_performance_indexes.py
    set /a deleted_count+=1
)

echo.
echo Cleanup complete!
echo   - Deleted %deleted_count% files
echo   - Backup saved in: %BACKUP_DIR%
echo.
echo Next steps:
echo   1. Run: alembic history
echo   2. Run: alembic check
echo   3. Test migrations: alembic upgrade head --sql
echo.
echo If issues occur, restore from backup:
echo   rmdir /S /Q alembic\versions
echo   move %BACKUP_DIR% alembic\versions
echo.
echo Hive Mind cleanup successful!
pause