from typing import List, Optional
from uuid import UUID
from datetime import date

from sqlalchemy import and_
from sqlalchemy.orm import Session, joinedload

from app.models.report import MedicalReport, Report
from app.models.patient import Patient
from app.repositories.base import BaseRepository
from app.utils.query_cache import cached_query


class MedicalReportRepository(BaseRepository[MedicalReport]):
    """Repository for MedicalReport model"""
    
    def __init__(self, db: Session):
        super().__init__(db, MedicalReport)
    
    @cached_query('reports_by_patient', ttl=300, tags=['reports'])
    def get_by_patient(self, patient_id: UUID, skip: int = 0, limit: int = 100, eager_load: bool = True) -> List[MedicalReport]:
        """
        Get medical reports by patient with eager loading and caching (5min TTL).

        PERFORMANCE OPTIMIZATION:
        - Eager loading prevents N+1 queries
        - Redis caching reduces DB load
        - Cache invalidated on report mutations

        Relationships loaded when eager_load=True:
        - patient: Patient information (joinedload - 1:1)
        - patient.doctor: Doctor information via patient (nested joinedload - 1:1)
        - generated_by_user: Doctor/user who generated the report (joinedload - 1:1)

        Args:
            patient_id: UUID of the patient
            skip: Pagination offset
            limit: Maximum records to return
            eager_load: Enable eager loading (default: True for performance)

        Returns:
            List of medical reports with relationships pre-loaded
        """
        from app.models.patient import Patient

        query = (
            self.db.query(MedicalReport)
            .filter(MedicalReport.patient_id == patient_id)
            .order_by(MedicalReport.created_at.desc())
        )

        if eager_load:
            # PERFORMANCE: Nested eager loading for complete relationship graph
            query = query.options(
                joinedload(MedicalReport.patient).joinedload(Patient.doctor),
                joinedload(MedicalReport.generated_by_user)
            )

        return query.offset(skip).limit(limit).all()
    
    def get_by_doctor(self, doctor_id: UUID, skip: int = 0, limit: int = 100, eager_load: bool = True) -> List[MedicalReport]:
        """
        Get reports generated by a doctor with eager loading.

        PERFORMANCE OPTIMIZATION: Eager loading enabled by default.

        Relationships loaded when eager_load=True:
        - patient: Patient information (joinedload - 1:1)
        - generated_by_user: Doctor/user who generated the report (joinedload - 1:1)

        Args:
            doctor_id: UUID of the doctor
            skip: Pagination offset
            limit: Maximum records to return
            eager_load: Enable eager loading (default: True for performance)

        Returns:
            List of medical reports with relationships pre-loaded
        """
        query = (
            self.db.query(MedicalReport)
            .filter(MedicalReport.generated_by == doctor_id)
            .order_by(MedicalReport.created_at.desc())
        )

        if eager_load:
            # PERFORMANCE: Load both patient and doctor to prevent N+1 queries
            query = query.options(
                joinedload(MedicalReport.patient),
                joinedload(MedicalReport.generated_by_user)
            )

        return query.offset(skip).limit(limit).all()
    
    def get_by_period(self, start_date: date, end_date: date, skip: int = 0, limit: int = 100) -> List[MedicalReport]:
        """Get reports by period"""
        return (
            self.db.query(MedicalReport)
            .filter(MedicalReport.period_start >= start_date)
            .filter(MedicalReport.period_end <= end_date)
            .order_by(MedicalReport.created_at.desc())
            .offset(skip)
            .limit(limit)
            .all()
        )
    
    def get_latest_for_patient(self, patient_id: UUID) -> Optional[MedicalReport]:
        """Get the latest report for a patient"""
        return (
            self.db.query(MedicalReport)
            .filter(MedicalReport.patient_id == patient_id)
            .order_by(MedicalReport.created_at.desc())
            .first()
        )
    
    def count_by_patient(self, patient_id: UUID) -> int:
        """Count reports for a specific patient"""
        return (
            self.db.query(MedicalReport)
            .filter(MedicalReport.patient_id == patient_id)
            .count()
        )
    
    def get_all_with_filters(
        self,
        skip: int = 0,
        limit: int = 100,
        patient_id: Optional[UUID] = None,
        doctor_id: Optional[UUID] = None
    ) -> List[MedicalReport]:
        """Get all reports with optional filters"""
        query = self.db.query(MedicalReport).options(joinedload(MedicalReport.patient))
        
        if patient_id:
            query = query.filter(MedicalReport.patient_id == patient_id)
        
        if doctor_id:
            query = query.join(Patient).filter(Patient.doctor_id == doctor_id)
        
        return (
            query
            .order_by(MedicalReport.created_at.desc())
            .offset(skip)
            .limit(limit)
            .all()
        )
    
    def count_with_filters(
        self,
        patient_id: Optional[UUID] = None,
        doctor_id: Optional[UUID] = None
    ) -> int:
        """Count reports with optional filters"""
        query = self.db.query(MedicalReport)
        
        if patient_id:
            query = query.filter(MedicalReport.patient_id == patient_id)
        
        if doctor_id:
            query = query.join(Patient).filter(Patient.doctor_id == doctor_id)
        
        return query.count()


class ReportRepository(BaseRepository[Report]):
    """Repository for generic Report model."""
    
    def __init__(self, db: Session):
        super().__init__(db, Report)
    
    def get_by_patient(self, patient_id: UUID, skip: int = 0, limit: int = 100) -> List[Report]:
        return (
            self.db.query(Report)
            .filter(Report.patient_id == patient_id)
            .order_by(Report.generated_at.desc())
            .offset(skip)
            .limit(limit)
            .all()
        )