from typing import List, Optional
from uuid import UUID
from datetime import date

from sqlalchemy import and_
from sqlalchemy.orm import Session, joinedload

from app.models.report import MedicalReport
from app.models.patient import Patient
from app.repositories.base import BaseRepository


class MedicalReportRepository(BaseRepository[MedicalReport]):
    """Repository for MedicalReport model"""
    
    def __init__(self, db: Session):
        super().__init__(db, MedicalReport)
    
    def get_by_patient(self, patient_id: UUID, skip: int = 0, limit: int = 100) -> List[MedicalReport]:
        """Get medical reports by patient"""
        return (
            self.db.query(MedicalReport)
            .filter(MedicalReport.patient_id == patient_id)
            .order_by(MedicalReport.created_at.desc())
            .offset(skip)
            .limit(limit)
            .all()
        )
    
    def get_by_doctor(self, doctor_id: UUID, skip: int = 0, limit: int = 100) -> List[MedicalReport]:
        """Get reports generated by a doctor"""
        return (
            self.db.query(MedicalReport)
            .filter(MedicalReport.generated_by == doctor_id)
            .order_by(MedicalReport.created_at.desc())
            .offset(skip)
            .limit(limit)
            .all()
        )
    
    def get_by_period(self, start_date: date, end_date: date, skip: int = 0, limit: int = 100) -> List[MedicalReport]:
        """Get reports by period"""
        return (
            self.db.query(MedicalReport)
            .filter(MedicalReport.period_start >= start_date)
            .filter(MedicalReport.period_end <= end_date)
            .order_by(MedicalReport.created_at.desc())
            .offset(skip)
            .limit(limit)
            .all()
        )
    
    def get_latest_for_patient(self, patient_id: UUID) -> Optional[MedicalReport]:
        """Get the latest report for a patient"""
        return (
            self.db.query(MedicalReport)
            .filter(MedicalReport.patient_id == patient_id)
            .order_by(MedicalReport.created_at.desc())
            .first()
        )
    
    def count_by_patient(self, patient_id: UUID) -> int:
        """Count reports for a specific patient"""
        return (
            self.db.query(MedicalReport)
            .filter(MedicalReport.patient_id == patient_id)
            .count()
        )
    
    def get_all_with_filters(
        self,
        skip: int = 0,
        limit: int = 100,
        patient_id: Optional[UUID] = None,
        doctor_id: Optional[UUID] = None
    ) -> List[MedicalReport]:
        """Get all reports with optional filters"""
        query = self.db.query(MedicalReport).options(joinedload(MedicalReport.patient))
        
        if patient_id:
            query = query.filter(MedicalReport.patient_id == patient_id)
        
        if doctor_id:
            query = query.join(Patient).filter(Patient.doctor_id == doctor_id)
        
        return (
            query
            .order_by(MedicalReport.created_at.desc())
            .offset(skip)
            .limit(limit)
            .all()
        )
    
    def count_with_filters(
        self,
        patient_id: Optional[UUID] = None,
        doctor_id: Optional[UUID] = None
    ) -> int:
        """Count reports with optional filters"""
        query = self.db.query(MedicalReport)
        
        if patient_id:
            query = query.filter(MedicalReport.patient_id == patient_id)
        
        if doctor_id:
            query = query.join(Patient).filter(Patient.doctor_id == doctor_id)
        
        return query.count()