"""
Report schemas for API validation.
"""
from datetime import date, datetime
from typing import List, Optional, Any
from uuid import UUID

from pydantic import BaseModel, Field, field_validator, ConfigDict


class ReportSectionSchema(BaseModel):
    """Report section schema."""
    title: str = Field(..., description="Section title")
    content: str = Field(..., description="Section content")
    subsections: List['ReportSectionSchema'] = Field(default_factory=list, description="Nested subsections")


class ReportGenerationRequest(BaseModel):
    """Request schema for report generation."""
    patient_id: UUID = Field(..., description="Patient ID")
    period_start: date = Field(..., description="Report period start date")
    period_end: date = Field(..., description="Report period end date")
    include_sections: List[str] = Field(
        default_factory=lambda: ["summary", "treatment", "symptoms", "adherence", "recommendations"],
        description="Sections to include in report"
    )
    format: str = Field(default="pdf", description="Report format (pdf, json)")

    @field_validator('period_end')
    @classmethod
    def validate_period(cls, v, info):
        if info.data.get('period_start') and v < info.data['period_start']:
            raise ValueError('period_end must be after period_start')
        return v


class ReportPreviewResponse(BaseModel):
    """Report preview response schema."""
    patient_name: str = Field(..., description="Patient name")
    patient_id: UUID = Field(..., description="Patient ID")
    doctor_name: str = Field(..., description="Doctor name")
    report_period: str = Field(..., description="Report period description")
    generated_date: datetime = Field(..., description="Report generation date")
    
    # Report sections
    executive_summary: str = Field(..., description="Executive summary")
    treatment_progress: ReportSectionSchema = Field(..., description="Treatment progress section")
    symptoms_analysis: ReportSectionSchema = Field(..., description="Symptoms analysis section")
    medication_adherence: ReportSectionSchema = Field(..., description="Medication adherence section")
    recommendations: ReportSectionSchema = Field(..., description="Recommendations section")
    
    # Data summaries
    quiz_responses_count: int = Field(..., description="Number of quiz responses")
    message_statistics: dict[str, Any] = Field(..., description="Message statistics")
    alert_count: int = Field(..., description="Number of alerts")


class MedicalReportResponse(BaseModel):
    """Medical report response schema."""
    id: UUID = Field(..., description="Report ID")
    patient_id: UUID = Field(..., description="Patient ID")
    generated_by: UUID = Field(..., description="Generated by user ID")
    period_start: date = Field(..., description="Report period start")
    period_end: date = Field(..., description="Report period end")
    summary: Optional[str] = Field(None, description="AI-generated summary")
    insights: dict[str, Any] = Field(default_factory=dict, description="Structured insights")
    charts_data: dict[str, Any] = Field(default_factory=dict, description="Chart data")
    alerts: dict[str, Any] = Field(default_factory=dict, description="Alert data")
    created_at: datetime = Field(..., description="Creation timestamp")
    updated_at: datetime = Field(..., description="Last update timestamp")

    model_config = ConfigDict(from_attributes=True)


class ReportListResponse(BaseModel):
    """Report list response schema."""
    reports: List[MedicalReportResponse] = Field(..., description="List of reports")
    total: int = Field(..., description="Total number of reports")
    page: int = Field(..., description="Current page")
    size: int = Field(..., description="Page size")
    pages: int = Field(..., description="Total pages")


class AnalyticsRequest(BaseModel):
    """Analytics request schema."""
    patient_ids: Optional[List[UUID]] = Field(None, description="Specific patient IDs")
    doctor_id: Optional[UUID] = Field(None, description="Filter by doctor")
    start_date: Optional[date] = Field(None, description="Start date for analytics")
    end_date: Optional[date] = Field(None, description="End date for analytics")
    metrics: List[str] = Field(
        default_factory=lambda: ["engagement", "adherence", "symptoms", "alerts"],
        description="Metrics to include"
    )


class PatientAnalytics(BaseModel):
    """Patient analytics data."""
    patient_id: UUID = Field(..., description="Patient ID")
    patient_name: str = Field(..., description="Patient name")
    treatment_type: Optional[str] = Field(None, description="Treatment type")
    current_day: int = Field(..., description="Current treatment day")
    
    # Engagement metrics
    total_messages_sent: int = Field(default=0, description="Total messages sent to patient")
    total_messages_received: int = Field(default=0, description="Total messages received from patient")
    response_rate: float = Field(default=0.0, description="Response rate percentage")
    avg_response_time_hours: Optional[float] = Field(None, description="Average response time in hours")
    
    # Quiz metrics
    quizzes_completed: int = Field(default=0, description="Number of completed quizzes")
    quiz_completion_rate: float = Field(default=0.0, description="Quiz completion rate percentage")
    avg_quiz_score: Optional[float] = Field(None, description="Average quiz score")
    
    # Alert metrics
    total_alerts: int = Field(default=0, description="Total alerts generated")
    high_priority_alerts: int = Field(default=0, description="High priority alerts")
    resolved_alerts: int = Field(default=0, description="Resolved alerts")
    
    # Trend data
    engagement_trend: List[dict[str, Any]] = Field(default_factory=list, description="Engagement trend data")
    symptom_trend: List[dict[str, Any]] = Field(default_factory=list, description="Symptom trend data")


class SystemAnalytics(BaseModel):
    """System-wide analytics data."""
    total_patients: int = Field(..., description="Total number of patients")
    active_patients: int = Field(..., description="Number of active patients")
    total_doctors: int = Field(..., description="Total number of doctors")
    
    # Message metrics
    total_messages_today: int = Field(default=0, description="Messages sent today")
    total_messages_week: int = Field(default=0, description="Messages sent this week")
    total_messages_month: int = Field(default=0, description="Messages sent this month")
    
    # Quiz metrics
    quizzes_completed_today: int = Field(default=0, description="Quizzes completed today")
    quizzes_completed_week: int = Field(default=0, description="Quizzes completed this week")
    
    # Alert metrics
    alerts_generated_today: int = Field(default=0, description="Alerts generated today")
    unresolved_alerts: int = Field(default=0, description="Unresolved alerts")
    
    # Performance metrics
    avg_response_time_ms: float = Field(default=0.0, description="Average API response time")
    system_uptime_hours: float = Field(default=0.0, description="System uptime in hours")


class AnalyticsResponse(BaseModel):
    """Analytics response schema."""
    patient_analytics: List[PatientAnalytics] = Field(default_factory=list, description="Patient-specific analytics")
    system_analytics: SystemAnalytics = Field(..., description="System-wide analytics")
    generated_at: datetime = Field(default_factory=datetime.utcnow, description="Analytics generation timestamp")


class DashboardResponse(BaseModel):
    """Dashboard data response schema."""
    # Quick stats
    total_patients: int = Field(..., description="Total patients")
    active_patients: int = Field(..., description="Active patients")
    messages_today: int = Field(..., description="Messages sent today")
    alerts_pending: int = Field(..., description="Pending alerts")

    # Derived/summary metrics for frontend dashboard
    active_patients_percentage: float = Field(0.0, description="Percentage of active patients")
    response_rate: float = Field(0.0, description="Overall response rate percentage (last 7 days)")
    messages_sent: int = Field(0, description="Messages sent in the last 7 days")
    completed_quizzes: int = Field(0, description="Quizzes completed in the last 7 days")
    avg_response_time: float = Field(0.0, description="Average response time in minutes (approx)")

    # Trend data (percentage changes from previous period)
    patients_change: float = Field(0.0, description="Percentage change in total patients from previous period")
    active_patients_change: float = Field(0.0, description="Percentage change in active patients from previous period")
    messages_change: float = Field(0.0, description="Percentage change in messages from previous period")
    alerts_change: float = Field(0.0, description="Percentage change in alerts from previous period")
    response_rate_change: float = Field(0.0, description="Percentage change in response rate from previous period")
    quizzes_change: float = Field(0.0, description="Percentage change in completed quizzes from previous period")

    # Recent activity
    recent_messages: List[dict[str, Any]] = Field(default_factory=list, description="Recent messages")
    recent_alerts: List[dict[str, Any]] = Field(default_factory=list, description="Recent alerts")
    recent_quiz_completions: List[dict[str, Any]] = Field(default_factory=list, description="Recent quiz completions")

    # Charts data
    engagement_chart: List[dict[str, Any]] = Field(default_factory=list, description="Daily engagement series with messages_sent, responses_received, response_rate")
    alert_severity_chart: dict[str, Any] = Field(default_factory=dict, description="Alert severity distribution")
    treatment_progress_chart: dict[str, Any] = Field(default_factory=dict, description="Treatment progress chart")

    generated_at: datetime = Field(default_factory=datetime.utcnow, description="Dashboard generation timestamp")


# Update forward references
ReportSectionSchema.model_rebuild()