"""Adiciona cascade delete na tabela patient_flow_states

Revision ID: 6319ddd51e92
Revises: 
Create Date: 2025-10-13 17:39:24.784017

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6319ddd51e92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Apenas adicionar CASCADE DELETE na tabela patient_flow_states
    op.execute("""
        ALTER TABLE patient_flow_states
        DROP CONSTRAINT IF EXISTS patient_flow_states_patient_id_fkey,
        ADD CONSTRAINT patient_flow_states_patient_id_fkey
        FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE patient_flow_states
        DROP CONSTRAINT IF EXISTS patient_flow_states_patient_id_fkey,
        ADD CONSTRAINT patient_flow_states_patient_id_fkey
        FOREIGN KEY (patient_id) REFERENCES patients(id)
    """)
    # ### end Alembic commands ###