"""create_missing_lgpd_tables

Revision ID: 9139c2862e40
Revises: 038_make_doctor_id_nullable
Create Date: 2026-01-01 18:26:16.172509

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9139c2862e40'
down_revision = '038_make_doctor_id_nullable'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create lgpd_audit_logs table
    op.create_table('lgpd_audit_logs',
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.Column('user_email', sa.String(length=255), nullable=True),
        sa.Column('user_role', sa.String(length=50), nullable=True),
        sa.Column('patient_id', sa.UUID(), nullable=True),
        sa.Column('patient_identifier', sa.String(length=255), nullable=True),
        sa.Column('action', sa.String(length=50), nullable=False),
        sa.Column('data_category', sa.String(length=50), nullable=False),
        sa.Column('resource_type', sa.String(length=100), nullable=False),
        sa.Column('resource_id', sa.String(length=255), nullable=True),
        sa.Column('fields_accessed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('fields_modified', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('purpose', sa.String(length=255), nullable=True),
        sa.Column('legal_basis', sa.String(length=100), nullable=True),
        sa.Column('ip_address', postgresql.INET(), nullable=True),
        sa.Column('user_agent', sa.String(length=500), nullable=True),
        sa.Column('session_id', sa.String(length=255), nullable=True),
        sa.Column('request_id', sa.String(length=255), nullable=True),
        sa.Column('additional_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('success', sa.Boolean(), nullable=False),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('retention_until', sa.DateTime(timezone=True), nullable=True),
        sa.Column('can_be_deleted', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Indexes for lgpd_audit_logs
    op.create_index(op.f('ix_lgpd_audit_logs_action'), 'lgpd_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_lgpd_audit_logs_data_category'), 'lgpd_audit_logs', ['data_category'], unique=False)
    op.create_index(op.f('ix_lgpd_audit_logs_id'), 'lgpd_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_lgpd_audit_logs_patient_id'), 'lgpd_audit_logs', ['patient_id'], unique=False)
    op.create_index(op.f('ix_lgpd_audit_logs_session_id'), 'lgpd_audit_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_lgpd_audit_logs_user_id'), 'lgpd_audit_logs', ['user_id'], unique=False)
    
    # Composite indexes
    op.create_index('ix_lgpd_audit_action_time', 'lgpd_audit_logs', ['action', 'created_at'], unique=False)
    op.create_index('ix_lgpd_audit_failures', 'lgpd_audit_logs', ['created_at'], unique=False, postgresql_where=sa.text('NOT success'))
    op.create_index('ix_lgpd_audit_patient_time', 'lgpd_audit_logs', ['patient_id', 'created_at'], unique=False)
    op.create_index('ix_lgpd_audit_session', 'lgpd_audit_logs', ['session_id', 'created_at'], unique=False)
    op.create_index('ix_lgpd_audit_user_time', 'lgpd_audit_logs', ['user_id', 'created_at'], unique=False)


    # Create lgpd_data_access_requests table
    op.create_table('lgpd_data_access_requests',
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('patient_id', sa.UUID(), nullable=False),
        sa.Column('requested_by', sa.String(length=255), nullable=True),
        sa.Column('verified', sa.Boolean(), nullable=False),
        sa.Column('request_type', sa.String(length=50), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('assigned_to_id', sa.UUID(), nullable=True),
        sa.Column('response', sa.Text(), nullable=True),
        sa.Column('rejection_reason', sa.Text(), nullable=True),
        sa.Column('evidence_url', sa.String(length=500), nullable=True),
        sa.Column('evidence_hash', sa.String(length=64), nullable=True),
        sa.Column('request_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Indexes for lgpd_data_access_requests
    op.create_index(op.f('ix_lgpd_data_access_requests_id'), 'lgpd_data_access_requests', ['id'], unique=False)
    op.create_index(op.f('ix_lgpd_data_access_requests_patient_id'), 'lgpd_data_access_requests', ['patient_id'], unique=False)
    op.create_index(op.f('ix_lgpd_data_access_requests_request_type'), 'lgpd_data_access_requests', ['request_type'], unique=False)
    op.create_index(op.f('ix_lgpd_data_access_requests_status'), 'lgpd_data_access_requests', ['status'], unique=False)
    op.create_index('ix_dsar_status_deadline', 'lgpd_data_access_requests', ['status', 'deadline_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lgpd_data_access_requests')
    op.drop_table('lgpd_audit_logs')
    # ### end Alembic commands ###