"""Add audit log entries table for platform integration

Revision ID: audit_log_entries_001
Revises: 
Create Date: 2025-08-13 16:52:19.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '006_audit_log'
down_revision = '005_quiz_sessions'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log_entries',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('patient_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('context_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('audit_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('request_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_entries_entity_id'), 'audit_log_entries', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_event_type'), 'audit_log_entries', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_id'), 'audit_log_entries', ['id'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_patient_id'), 'audit_log_entries', ['patient_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_request_id'), 'audit_log_entries', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_session_id'), 'audit_log_entries', ['session_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_timestamp'), 'audit_log_entries', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_user_id'), 'audit_log_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_log_entries_user_id'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_timestamp'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_session_id'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_request_id'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_patient_id'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_id'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_event_type'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_entity_id'), table_name='audit_log_entries')
    op.drop_table('audit_log_entries')
    # ### end Alembic commands ###