apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hormonia-quiz
spec:
  template:
    spec:
      containers:
        - image: REPLACE_WITH_IMAGE
          ports:
            - containerPort: 8080
