apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: clinica-quiz
spec:
  template:
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/woven-framework-484323-n7/clinica-repo/quiz-interface:20260121-131733
        ports:
        - containerPort: 8080
        env:
        - name: TZ
          value: America/Sao_Paulo
