-- ============================================================================
-- 🧠 HIVE MIND GENERATED: Production Database Alembic Stamp Script
-- ============================================================================
-- CRITICAL MISSION: Safely stamp production database with correct Alembic version
-- Generated by: ALEMBIC SCRIPT GENERATOR agent (Hive Mind Collective)
-- Date: 2025-10-09
-- Target Version: 20251010_000000 (latest production migration)
--
-- BASED ON HIVE ANALYSIS:
-- - Production database: 38 tables + 5 materialized views
-- - Firebase integration: Complete with 9 fields + user_sync_log
-- - Latest migration: 20251010_000000_add_unique_quiz_session_constraint
-- - Performance optimizations: 23+ new indexes including GIN search
-- - Migration chain: Verified through 69 total migrations
--
-- SAFETY FEATURES:
-- ✅ Pre-flight verification checks
-- ✅ Backup current state before changes
-- ✅ Rollback procedures included
-- ✅ Comprehensive validation queries
-- ✅ Production environment safeguards
-- ✅ Error handling with detailed messages
-- ============================================================================

\echo '🧠 HIVE MIND ALEMBIC STAMP SCRIPT INITIATED'
\echo '=' '=' '=' '=' '=' '=' '=' '=' '=' '=' '=' '=' '=' '=' '=' '=' '=' '=' '=' '='

-- Set safe transaction mode
\set ON_ERROR_STOP on
\set AUTOCOMMIT off

BEGIN;

-- ============================================================================
-- STEP 1: ENVIRONMENT VERIFICATION
-- ============================================================================
\echo 'STEP 1: Verifying production environment...'

-- Check PostgreSQL version (minimum 12.0 required)
DO $$
DECLARE
    pg_version_num INTEGER;
BEGIN
    SELECT current_setting('server_version_num')::INTEGER INTO pg_version_num;
    IF pg_version_num < 120000 THEN
        RAISE EXCEPTION 'PostgreSQL version too old: %. Minimum required: 12.0', version();
    END IF;
    RAISE NOTICE '✅ PostgreSQL version verified: %', version();
END $$;

-- Check database name (safety check)
DO $$
DECLARE
    db_name TEXT;
BEGIN
    SELECT current_database() INTO db_name;
    RAISE NOTICE '📋 Database: %', db_name;

    -- Warning for non-production-like names
    IF db_name NOT ILIKE '%prod%' AND db_name NOT ILIKE '%production%' THEN
        RAISE WARNING '⚠️ Database name "%" does not appear to be production. Verify this is correct!', db_name;
    END IF;
END $$;

-- ============================================================================
-- STEP 2: CURRENT STATE BACKUP
-- ============================================================================
\echo 'STEP 2: Creating backup of current Alembic state...'

-- Create backup table for current state
DROP TABLE IF EXISTS alembic_version_backup_20251009;

CREATE TABLE alembic_version_backup_20251009 AS
SELECT
    version_num,
    NOW() as backup_timestamp,
    'Pre-stamp backup by Hive Mind script' as backup_reason
FROM alembic_version;

-- Check if backup was created
DO $$
DECLARE
    backup_count INTEGER;
    current_version TEXT;
BEGIN
    SELECT COUNT(*) INTO backup_count FROM alembic_version_backup_20251009;

    IF backup_count > 0 THEN
        SELECT version_num INTO current_version FROM alembic_version_backup_20251009;
        RAISE NOTICE '✅ Backup created. Current version: %', current_version;
    ELSE
        RAISE NOTICE '⚠️ No existing version to backup (fresh database)';
    END IF;
END $$;

-- ============================================================================
-- STEP 3: SCHEMA INTEGRITY VERIFICATION
-- ============================================================================
\echo 'STEP 3: Verifying schema integrity based on hive analysis...'

-- 3.1 Check critical tables exist
\echo '3.1 Verifying core tables...'
DO $$
DECLARE
    expected_tables TEXT[] := ARRAY[
        'users', 'patients', 'messages', 'alerts', 'quiz_sessions',
        'user_sync_log', 'whatsapp_delivery_failures', 'webhook_events',
        'quiz_templates', 'quiz_responses', 'medical_reports',
        'patient_flow_states', 'ab_experiments', 'audit_logs'
    ];
    table_name TEXT;
    missing_tables TEXT[] := ARRAY[]::TEXT[];
    table_exists BOOLEAN;
BEGIN
    FOREACH table_name IN ARRAY expected_tables LOOP
        SELECT EXISTS (
            SELECT FROM information_schema.tables
            WHERE table_name = table_name AND table_schema = 'public'
        ) INTO table_exists;

        IF NOT table_exists THEN
            missing_tables := array_append(missing_tables, table_name);
        END IF;
    END LOOP;

    IF array_length(missing_tables, 1) > 0 THEN
        RAISE EXCEPTION '❌ Missing critical tables: %', array_to_string(missing_tables, ', ');
    ELSE
        RAISE NOTICE '✅ All % critical tables verified', array_length(expected_tables, 1);
    END IF;
END $$;

-- 3.2 Check Firebase integration in users table
\echo '3.2 Verifying Firebase integration...'
DO $$
DECLARE
    firebase_fields TEXT[] := ARRAY[
        'firebase_uid', 'auth_provider', 'firebase_last_sign_in',
        'firebase_created_at', 'firebase_email_verified',
        'firebase_display_name', 'firebase_photo_url',
        'firebase_custom_claims', 'last_firebase_sync'
    ];
    field_name TEXT;
    missing_fields TEXT[] := ARRAY[]::TEXT[];
    field_exists BOOLEAN;
BEGIN
    FOREACH field_name IN ARRAY firebase_fields LOOP
        SELECT EXISTS (
            SELECT FROM information_schema.columns
            WHERE table_name = 'users'
            AND column_name = field_name
            AND table_schema = 'public'
        ) INTO field_exists;

        IF NOT field_exists THEN
            missing_fields := array_append(missing_fields, field_name);
        END IF;
    END LOOP;

    IF array_length(missing_fields, 1) > 0 THEN
        RAISE EXCEPTION '❌ Missing Firebase fields in users table: %', array_to_string(missing_fields, ', ');
    ELSE
        RAISE NOTICE '✅ Firebase integration complete (9/9 fields)';
    END IF;
END $$;

-- 3.3 Check user_sync_log table completeness
\echo '3.3 Verifying user_sync_log table...'
DO $$
DECLARE
    required_columns TEXT[] := ARRAY[
        'id', 'firebase_uid', 'user_id', 'operation',
        'sync_direction', 'changes', 'success', 'error_message',
        'created_at', 'updated_at'
    ];
    column_name TEXT;
    missing_columns TEXT[] := ARRAY[]::TEXT[];
    column_exists BOOLEAN;
BEGIN
    FOREACH column_name IN ARRAY required_columns LOOP
        SELECT EXISTS (
            SELECT FROM information_schema.columns
            WHERE table_name = 'user_sync_log'
            AND column_name = column_name
            AND table_schema = 'public'
        ) INTO column_exists;

        IF NOT column_exists THEN
            missing_columns := array_append(missing_columns, column_name);
        END IF;
    END LOOP;

    IF array_length(missing_columns, 1) > 0 THEN
        RAISE EXCEPTION '❌ Missing user_sync_log columns: %', array_to_string(missing_columns, ', ');
    ELSE
        RAISE NOTICE '✅ user_sync_log table complete with updated_at fix';
    END IF;
END $$;

-- 3.4 Check critical ENUM types
\echo '3.4 Verifying ENUM types...'
DO $$
DECLARE
    expected_enums TEXT[] := ARRAY[
        'user_role', 'flow_state', 'message_direction', 'message_type',
        'message_status', 'alert_severity', 'deliverystatus'
    ];
    enum_name TEXT;
    missing_enums TEXT[] := ARRAY[]::TEXT[];
    enum_exists BOOLEAN;
    existing_count INTEGER;
BEGIN
    FOREACH enum_name IN ARRAY expected_enums LOOP
        SELECT EXISTS (
            SELECT FROM pg_type
            WHERE typname = enum_name AND typtype = 'e'
        ) INTO enum_exists;

        IF NOT enum_exists THEN
            missing_enums := array_append(missing_enums, enum_name);
        END IF;
    END LOOP;

    -- Count existing enums
    SELECT COUNT(*) INTO existing_count
    FROM pg_type
    WHERE typtype = 'e';

    IF array_length(missing_enums, 1) > 0 THEN
        RAISE WARNING '⚠️ Missing ENUM types: % (found % total)', array_to_string(missing_enums, ', '), existing_count;
    ELSE
        RAISE NOTICE '✅ All % critical ENUM types found', array_length(expected_enums, 1);
    END IF;
END $$;

-- 3.5 Check critical indexes (performance verification)
\echo '3.5 Verifying critical indexes...'
DO $$
DECLARE
    critical_indexes TEXT[] := ARRAY[
        'idx_users_firebase_uid', 'idx_users_auth_provider',
        'idx_patients_name_gin_trgm', 'idx_messages_content_gin_trgm',
        'idx_alerts_patient_status_created', 'ix_quiz_session_patient_template_month_unique'
    ];
    index_name TEXT;
    missing_indexes TEXT[] := ARRAY[]::TEXT[];
    index_exists BOOLEAN;
    total_indexes INTEGER;
BEGIN
    FOREACH index_name IN ARRAY critical_indexes LOOP
        SELECT EXISTS (
            SELECT FROM pg_indexes
            WHERE indexname = index_name AND schemaname = 'public'
        ) INTO index_exists;

        IF NOT index_exists THEN
            missing_indexes := array_append(missing_indexes, index_name);
        END IF;
    END LOOP;

    -- Count total indexes
    SELECT COUNT(*) INTO total_indexes
    FROM pg_indexes
    WHERE schemaname = 'public';

    IF array_length(missing_indexes, 1) > 0 THEN
        RAISE WARNING '⚠️ Missing critical indexes: % (found % total)', array_to_string(missing_indexes, ', '), total_indexes;
    ELSE
        RAISE NOTICE '✅ All critical indexes found (% total indexes)', total_indexes;
    END IF;
END $$;

-- ============================================================================
-- STEP 4: ALEMBIC VERSION MANAGEMENT
-- ============================================================================
\echo 'STEP 4: Managing Alembic version...'

-- Check if alembic_version table exists
DO $$
DECLARE
    table_exists BOOLEAN;
    current_version TEXT;
    target_version TEXT := '20251010_000000';
BEGIN
    SELECT EXISTS (
        SELECT FROM information_schema.tables
        WHERE table_name = 'alembic_version' AND table_schema = 'public'
    ) INTO table_exists;

    IF table_exists THEN
        -- Get current version
        SELECT version_num INTO current_version FROM alembic_version LIMIT 1;

        IF current_version IS NULL THEN
            RAISE NOTICE '⚠️ alembic_version table exists but is empty';
        ELSIF current_version = target_version THEN
            RAISE NOTICE '✅ Database already stamped with target version: %', target_version;
            RETURN;
        ELSE
            RAISE NOTICE '📋 Current version: %, Target: %', current_version, target_version;
        END IF;
    ELSE
        RAISE NOTICE '⚠️ alembic_version table does not exist - will create';
    END IF;
END $$;

-- ============================================================================
-- STEP 5: PERFORM ALEMBIC STAMP
-- ============================================================================
\echo 'STEP 5: Performing Alembic stamp...'

-- Create or update alembic_version table
DO $$
DECLARE
    table_exists BOOLEAN;
    target_version TEXT := '20251010_000000';
    rows_updated INTEGER;
BEGIN
    SELECT EXISTS (
        SELECT FROM information_schema.tables
        WHERE table_name = 'alembic_version' AND table_schema = 'public'
    ) INTO table_exists;

    IF table_exists THEN
        -- Update existing table
        UPDATE alembic_version SET version_num = target_version;
        GET DIAGNOSTICS rows_updated = ROW_COUNT;

        IF rows_updated = 0 THEN
            -- No existing rows, insert new one
            INSERT INTO alembic_version (version_num) VALUES (target_version);
            RAISE NOTICE '✅ Inserted new version: %', target_version;
        ELSE
            RAISE NOTICE '✅ Updated existing version to: %', target_version;
        END IF;
    ELSE
        -- Create table and insert version
        CREATE TABLE alembic_version (
            version_num VARCHAR(32) NOT NULL,
            CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
        );

        INSERT INTO alembic_version (version_num) VALUES (target_version);
        RAISE NOTICE '✅ Created alembic_version table with version: %', target_version;
    END IF;
END $$;

-- ============================================================================
-- STEP 6: VERIFICATION AND VALIDATION
-- ============================================================================
\echo 'STEP 6: Verifying stamp success...'

-- Verify stamp was successful
DO $$
DECLARE
    stamped_version TEXT;
    target_version TEXT := '20251010_000000';
BEGIN
    SELECT version_num INTO stamped_version FROM alembic_version LIMIT 1;

    IF stamped_version = target_version THEN
        RAISE NOTICE '✅ Stamp verification SUCCESSFUL: %', stamped_version;
    ELSE
        RAISE EXCEPTION '❌ Stamp verification FAILED. Expected: %, Found: %', target_version, stamped_version;
    END IF;
END $$;

-- Generate database statistics for verification report
\echo 'Generating verification statistics...'

SELECT
    '📊 DATABASE VERIFICATION REPORT' as report_section,
    current_database() as database_name,
    version() as postgresql_version,
    NOW() as verification_timestamp;

SELECT
    '📋 SCHEMA STATISTICS' as report_section,
    COUNT(*) as total_tables
FROM information_schema.tables
WHERE table_schema = 'public' AND table_type = 'BASE TABLE';

SELECT
    '📋 INDEX STATISTICS' as report_section,
    COUNT(*) as total_indexes
FROM pg_indexes
WHERE schemaname = 'public';

SELECT
    '📋 ENUM STATISTICS' as report_section,
    COUNT(*) as total_enums
FROM pg_type
WHERE typtype = 'e';

-- Check materialized views (performance feature)
SELECT
    '📋 MATERIALIZED VIEWS' as report_section,
    COUNT(*) as total_materialized_views
FROM pg_matviews
WHERE schemaname = 'public';

-- Show current Alembic version
SELECT
    '🎯 ALEMBIC STATUS' as report_section,
    version_num as current_version,
    '20251010_000000' as target_version,
    CASE WHEN version_num = '20251010_000000' THEN '✅ SUCCESS' ELSE '❌ MISMATCH' END as status
FROM alembic_version;

-- ============================================================================
-- STEP 7: COMMIT TRANSACTION
-- ============================================================================
\echo 'STEP 7: Committing transaction...'

COMMIT;

\echo '=' '=' '=' '=' '=' '=' '=' '=' '=' '=' '=' '=' '=' '=' '=' '=' '=' '=' '=' '='
\echo '✅ HIVE MIND ALEMBIC STAMP COMPLETED SUCCESSFULLY'
\echo '📋 Database stamped with version: 20251010_000000'
\echo '🧠 Hive Mind verification: PASSED'
\echo '=' '=' '=' '=' '=' '=' '=' '=' '=' '=' '=' '=' '=' '=' '=' '=' '=' '=' '=' '='

-- ============================================================================
-- ROLLBACK PROCEDURES (FOR EMERGENCY USE)
-- ============================================================================
\echo ''
\echo '🚨 ROLLBACK PROCEDURES (Emergency Use Only)'
\echo '============================================'
\echo ''
\echo 'If you need to rollback this stamp operation:'
\echo ''
\echo '1. Restore from backup table:'
\echo '   UPDATE alembic_version SET version_num = ('
\echo '       SELECT version_num FROM alembic_version_backup_20251009 LIMIT 1'
\echo '   );'
\echo ''
\echo '2. Or manually set to previous version:'
\echo '   UPDATE alembic_version SET version_num = '\''YOUR_PREVIOUS_VERSION'\'';'
\echo ''
\echo '3. Verify rollback:'
\echo '   SELECT version_num FROM alembic_version;'
\echo ''
\echo '4. Clean up backup table (optional):'
\echo '   DROP TABLE alembic_version_backup_20251009;'
\echo ''

-- ============================================================================
-- VERIFICATION QUERIES (FOR POST-STAMP CHECKS)
-- ============================================================================
\echo '🔍 POST-STAMP VERIFICATION QUERIES'
\echo '==================================='
\echo ''
\echo 'Run these queries to verify the stamp was successful:'
\echo ''
\echo '-- Check current Alembic version'
\echo 'SELECT version_num FROM alembic_version;'
\echo ''
\echo '-- Verify critical tables exist'
\echo 'SELECT table_name FROM information_schema.tables'
\echo 'WHERE table_schema = '\''public'\'' AND table_type = '\''BASE TABLE'\'''
\echo 'ORDER BY table_name;'
\echo ''
\echo '-- Check Firebase fields in users table'
\echo 'SELECT column_name, data_type, is_nullable'
\echo 'FROM information_schema.columns'
\echo 'WHERE table_name = '\''users'\'' AND column_name LIKE '\''firebase_%'\'''
\echo 'ORDER BY column_name;'
\echo ''
\echo '-- Verify user_sync_log table'
\echo '\d user_sync_log'
\echo ''
\echo '-- Check performance indexes'
\echo 'SELECT indexname, indexdef FROM pg_indexes'
\echo 'WHERE indexname LIKE '\''%gin_trgm%'\'' OR indexname LIKE '\''%quiz_session%'\'';'
\echo ''

-- ============================================================================
-- END OF SCRIPT
-- ============================================================================
\echo '🧠 Hive Mind Alembic Stamp Script completed at:'
SELECT NOW() as completion_time;